<?php

namespace Aliuwahab\ContinentCountrySeeder\Commands;

use Aliuwahab\ContinentCountrySeeder\Models\Continent;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class ContinentCountrySeederCommand extends Command
{
    public $signature = 'continent-country-seeder';

    public $description = 'My command';

    public function handle(): int
    {
        $this->comment('All done');

//        return self::SUCCESS;

        $europe = Continent::create(['name' => 'Europe']);
        $africa = Continent::create(['name' => 'Africa']);
        $asia = Continent::create(['name' => 'Asia']);
        $northAmerica = Continent::create(['name' => 'North America']);
        $southAmerica = Continent::create(['name' => 'South America']);
        $australiaOceania = Continent::create(['name' => 'Australia/Oceania']);
        $antartica = Continent::create(['name' => 'Antarctica']);

        DB::table('countries')->delete();

        $countries = [
            ['code' => 'GH', 'name' => 'Ghana', 'continent_id' => $africa->id, 'currency' => 'GHS'],
            ['code' => 'NG', 'name' => 'Nigeria', 'continent_id' => $africa->id,  'currency' => 'NGN'],
            ['code' => 'ZA', 'name' => 'South Africa', 'continent_id' => $africa->id, 'currency' => 'ZAR'],
            ['code' => 'US', 'name' => 'United States', 'continent_id' => $northAmerica->id],
            ['code' => 'CA', 'name' => 'Canada', 'continent_id' => $northAmerica->id],
            ['code' => 'AF', 'name' => 'Afghanistan', 'continent_id' => $asia->id],
            ['code' => 'AL', 'name' => 'Albania', 'continent_id' => $europe->id],
            ['code' => 'DZ', 'name' => 'Algeria', 'continent_id' => $africa->id],
            ['code' => 'AD', 'name' => 'Andorra', 'continent_id' => $europe->id],
            ['code' => 'AO', 'name' => 'Angola', 'continent_id' => $africa->id],
            ['code' => 'AR', 'name' => 'Argentina', 'continent_id' => $southAmerica->id],
            ['code' => 'AM', 'name' => 'Armenia', 'continent_id' => $europe->id],
            ['code' => 'AU', 'name' => 'Australia', 'continent_id' => $australiaOceania->id],
            ['code' => 'AT', 'name' => 'Austria', 'continent_id' => $europe->id],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'continent_id' => $europe->id],
            ['code' => 'BH', 'name' => 'Bahrain', 'continent_id' => $asia->id],
            ['code' => 'BD', 'name' => 'Bangladesh', 'continent_id' => $asia->id],
            ['code' => 'BB', 'name' => 'Barbados', 'continent_id' => $northAmerica->id],
            ['code' => 'BY', 'name' => 'Belarus', 'continent_id' => $europe->id],
            ['code' => 'BE', 'name' => 'Belgium', 'continent_id' => $europe->id],
            ['code' => 'BJ', 'name' => 'Benin', 'continent_id' => $africa->id],
            ['code' => 'BO', 'name' => 'Bolivia', 'continent_id' => $southAmerica->id],
            ['code' => 'BA', 'name' => 'Bosnia', 'continent_id' => $europe->id],
            ['code' => 'BW', 'name' => 'Botswana', 'continent_id' => $africa->id],
            ['code' => 'BR', 'name' => 'Brazil', 'continent_id' => $southAmerica->id],
            ['code' => 'BG', 'name' => 'Bulgaria', 'continent_id' => $europe->id],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'continent_id' => $africa->id],
            ['code' => 'BI', 'name' => 'Burundi', 'continent_id' => $africa->id],
            ['code' => 'KH', 'name' => 'Cambodia', 'continent_id' => $asia->id],
            ['code' => 'CM', 'name' => 'Cameroon', 'continent_id' => $africa->id],
            ['code' => 'CV', 'name' => 'Cape Verde', 'continent_id' => $africa->id],
            ['code' => 'CF', 'name' => 'Central African Republic', 'continent_id' => $africa->id],
            ['code' => 'TD', 'name' => 'Chad', 'continent_id' => $africa->id],
            ['code' => 'CL', 'name' => 'Chile', 'continent_id' => $southAmerica->id],
            ['code' => 'CN', 'name' => 'China', 'continent_id' => $asia->id],
            ['code' => 'CO', 'name' => 'Colombia', 'continent_id' => $southAmerica->id],
            ['code' => 'KM', 'name' => 'Comoros', 'continent_id' => $africa->id],
            ['code' => 'CG', 'name' => 'Congo', 'continent_id' => $africa->id],
            ['code' => 'CR', 'name' => 'Costa Rica', 'continent_id' => $africa->id],
            ['code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'continent_id' => $africa->id],
            ['code' => 'CU', 'name' => 'Cuba', 'continent_id' => $africa->id],
            ['code' => 'CY', 'name' => 'Cyprus', 'continent_id' => $africa->id],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'continent_id' => $africa->id],
            ['code' => 'CD', 'name' => 'Democratic Republic of Congo', 'continent_id' => $africa->id],
            ['code' => 'DK', 'name' => 'Denmark', 'continent_id' => $africa->id],
            ['code' => 'DJ', 'name' => 'Djibouti', 'continent_id' => $africa->id],
            ['code' => 'DM', 'name' => 'Dominica', 'continent_id' => $africa->id],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'continent_id' => $africa->id],
            ['code' => 'EC', 'name' => 'Ecudaor', 'continent_id' => $africa->id],
            ['code' => 'EG', 'name' => 'Egypt', 'continent_id' => $africa->id],
            ['code' => 'SV', 'name' => 'El Salvador', 'continent_id' => $africa->id],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'continent_id' => $africa->id],
            ['code' => 'ER', 'name' => 'Eritrea', 'continent_id' => $africa->id],
            ['code' => 'EE', 'name' => 'Estonia', 'continent_id' => $europe->id],
            ['code' => 'ET', 'name' => 'Ethiopia', 'continent_id' => $africa->id],
            ['code' => 'FI', 'name' => 'Finland', 'continent_id' => $africa->id],
            ['code' => 'FR', 'name' => 'France', 'continent_id' => $africa->id],
            ['code' => 'GA', 'name' => 'Gabon', 'continent_id' => $africa->id],
            ['code' => 'GM', 'name' => 'Gambia', 'continent_id' => $africa->id],
            ['code' => 'GE', 'name' => 'Georgia', 'continent_id' => $africa->id],
            ['code' => 'DE', 'name' => 'Germany', 'continent_id' => $africa->id],
            ['code' => 'GI', 'name' => 'Gibraltar', 'continent_id' => $africa->id],
            ['code' => 'GR', 'name' => 'Greece', 'continent_id' => $africa->id],
            ['code' => 'GL', 'name' => 'Greenland', 'continent_id' => $africa->id],
            ['code' => 'GD', 'name' => 'Grenada', 'continent_id' => $africa->id],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'continent_id' => $africa->id],
            ['code' => 'GU', 'name' => 'Guam', 'continent_id' => $africa->id],
            ['code' => 'GT', 'name' => 'Guatemala', 'continent_id' => $africa->id],
            ['code' => 'GN', 'name' => 'Guinea', 'continent_id' => $africa->id],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'continent_id' => $africa->id],
            ['code' => 'GY', 'name' => 'Guyana', 'continent_id' => $africa->id],
            ['code' => 'HT', 'name' => 'Haiti', 'continent_id' => $africa->id],
            ['code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'continent_id' => $africa->id],
            ['code' => 'HN', 'name' => 'Honduras', 'continent_id' => $africa->id],
            ['code' => 'HK', 'name' => 'Hong Kong', 'continent_id' => $africa->id],
            ['code' => 'HU', 'name' => 'Hungary', 'continent_id' => $africa->id],
            ['code' => 'IS', 'name' => 'Iceland', 'continent_id' => $africa->id],
            ['code' => 'IN', 'name' => 'India', 'continent_id' => $africa->id],
            ['code' => 'ID', 'name' => 'Indonesia', 'continent_id' => $africa->id],
            ['code' => 'IR', 'name' => 'Iran (Islamic Republic of)', 'continent_id' => $africa->id],
            ['code' => 'IQ', 'name' => 'Iraq', 'continent_id' => $africa->id],
            ['code' => 'IE', 'name' => 'Ireland', 'continent_id' => $africa->id],
            ['code' => 'IL', 'name' => 'Israel', 'continent_id' => $africa->id],
            ['code' => 'IT', 'name' => 'Italy', 'continent_id' => $africa->id],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'continent_id' => $africa->id],
            ['code' => 'JM', 'name' => 'Jamaica', 'continent_id' => $africa->id],
            ['code' => 'JP', 'name' => 'Japan', 'continent_id' => $africa->id],
            ['code' => 'JO', 'name' => 'Jordan', 'continent_id' => $africa->id],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'continent_id' => $africa->id],
            ['code' => 'KE', 'name' => 'Kenya', 'continent_id' => $africa->id],
            ['code' => 'KI', 'name' => 'Kiribati', 'continent_id' => $africa->id],
            ['code' => 'KR', 'name' => 'South Korea', 'continent_id' => $africa->id],
            ['code' => 'KP', 'name' => 'North Korea', 'continent_id' => $africa->id],
            ['code' => 'KW', 'name' => 'Kuwait', 'continent_id' => $africa->id],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'continent_id' => $africa->id],
            ['code' => 'LV', 'name' => 'Latvia', 'continent_id' => $africa->id],
            ['code' => 'LB', 'name' => 'Lebanon', 'continent_id' => $africa->id],
            ['code' => 'LS', 'name' => 'Lesotho', 'continent_id' => $africa->id],
            ['code' => 'LR', 'name' => 'Liberia', 'continent_id' => $africa->id],
            ['code' => 'LY', 'name' => 'Libya', 'continent_id' => $africa->id],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'continent_id' => $africa->id],
            ['code' => 'LT', 'name' => 'Lithuania', 'continent_id' => $africa->id],
            ['code' => 'LU', 'name' => 'Luxembourg', 'continent_id' => $africa->id],
            ['code' => 'MO', 'name' => 'Macau', 'continent_id' => $africa->id],
            ['code' => 'MK', 'name' => 'Macedonia', 'continent_id' => $africa->id],
            ['code' => 'MG', 'name' => 'Madagascar', 'continent_id' => $africa->id],
            ['code' => 'MW', 'name' => 'Malawi', 'continent_id' => $africa->id],
            ['code' => 'MY', 'name' => 'Malaysia', 'continent_id' => $africa->id],
            ['code' => 'MV', 'name' => 'Maldives', 'continent_id' => $africa->id],
            ['code' => 'ML', 'name' => 'Mali', 'continent_id' => $africa->id],
            ['code' => 'MT', 'name' => 'Malta', 'continent_id' => $africa->id],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'continent_id' => $africa->id],
            ['code' => 'MQ', 'name' => 'Martinique', 'continent_id' => $africa->id],
            ['code' => 'MR', 'name' => 'Mauritania', 'continent_id' => $africa->id],
            ['code' => 'MU', 'name' => 'Mauritius', 'continent_id' => $africa->id],
            ['code' => 'TY', 'name' => 'Mayotte', 'continent_id' => $africa->id],
            ['code' => 'MX', 'name' => 'Mexico', 'continent_id' => $africa->id],
            ['code' => 'MN', 'name' => 'Mongolia', 'continent_id' => $africa->id],
            ['code' => 'MA', 'name' => 'Morocco', 'continent_id' => $africa->id],
            ['code' => 'MZ', 'name' => 'Mozambique', 'continent_id' => $africa->id],
            ['code' => 'MM', 'name' => 'Myanmar', 'continent_id' => $africa->id],
            ['code' => 'NA', 'name' => 'Namibia', 'continent_id' => $africa->id],
            ['code' => 'NP', 'name' => 'Nepal', 'continent_id' => $africa->id],
            ['code' => 'NL', 'name' => 'Netherlands', 'continent_id' => $africa->id],
            ['code' => 'AN', 'name' => 'Netherlands Antilles', 'continent_id' => $africa->id],
            ['code' => 'NZ', 'name' => 'New Zealand', 'continent_id' => $africa->id],
            ['code' => 'NI', 'name' => 'Nicaragua', 'continent_id' => $africa->id],
            ['code' => 'NE', 'name' => 'Niger', 'continent_id' => $africa->id],
            ['code' => 'NO', 'name' => 'Norway', 'continent_id' => $africa->id],
            ['code' => 'OM', 'name' => 'Oman', 'continent_id' => $africa->id],
            ['code' => 'PK', 'name' => 'Pakistan', 'continent_id' => $africa->id],
            ['code' => 'PA', 'name' => 'Panama'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'continent_id' => $africa->id],
            ['code' => 'PY', 'name' => 'Paraguay', 'continent_id' => $africa->id],
            ['code' => 'PE', 'name' => 'Peru', 'continent_id' => $africa->id],
            ['code' => 'PH', 'name' => 'Philippines', 'continent_id' => $africa->id],
            ['code' => 'PN', 'name' => 'Pitcairn', 'continent_id' => $africa->id],
            ['code' => 'PL', 'name' => 'Poland', 'continent_id' => $africa->id],
            ['code' => 'PT', 'name' => 'Portugal', 'continent_id' => $africa->id],
            ['code' => 'QA', 'name' => 'Qatar', 'continent_id' => $africa->id],
            ['code' => 'SS', 'name' => 'Republic of South Sudan', 'continent_id' => $africa->id],
            ['code' => 'RO', 'name' => 'Romania', 'continent_id' => $africa->id],
            ['code' => 'RU', 'name' => 'Russia', 'continent_id' => $africa->id],
            ['code' => 'RW', 'name' => 'Rwanda', 'continent_id' => $africa->id],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'continent_id' => $africa->id],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'continent_id' => $africa->id],
            ['code' => 'SN', 'name' => 'Senegal', 'continent_id' => $africa->id],
            ['code' => 'RS', 'name' => 'Serbia', 'continent_id' => $africa->id],
            ['code' => 'SC', 'name' => 'Seychelles', 'continent_id' => $africa->id],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'continent_id' => $africa->id],
            ['code' => 'SG', 'name' => 'Singapore', 'continent_id' => $africa->id],
            ['code' => 'SK', 'name' => 'Slovakia', 'continent_id' => $africa->id],
            ['code' => 'SI', 'name' => 'Slovenia', 'continent_id' => $africa->id],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'continent_id' => $africa->id],
            ['code' => 'SO', 'name' => 'Somalia', 'continent_id' => $africa->id],
            ['code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'continent_id' => $africa->id],
            ['code' => 'ES', 'name' => 'Spain', 'continent_id' => $africa->id],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'continent_id' => $africa->id],
            ['code' => 'SD', 'name' => 'Sudan', 'continent_id' => $africa->id],
            ['code' => 'SR', 'name' => 'Suriname', 'continent_id' => $africa->id],
            ['code' => 'SZ', 'name' => 'Swaziland', 'continent_id' => $africa->id],
            ['code' => 'SE', 'name' => 'Sweden', 'continent_id' => $africa->id],
            ['code' => 'CH', 'name' => 'Switzerland', 'continent_id' => $africa->id],
            ['code' => 'SY', 'name' => 'Syrian Arab Republic', 'continent_id' => $africa->id],
            ['code' => 'TW', 'name' => 'Taiwan', 'continent_id' => $africa->id],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'continent_id' => $africa->id],
            ['code' => 'TZ', 'name' => 'Tanzania', 'continent_id' => $africa->id],
            ['code' => 'TH', 'name' => 'Thailand', 'continent_id' => $africa->id],
            ['code' => 'TG', 'name' => 'Togo', 'continent_id' => $africa->id],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'continent_id' => $africa->id],
            ['code' => 'TN', 'name' => 'Tunisia', 'continent_id' => $africa->id],
            ['code' => 'TR', 'name' => 'Turkey', 'continent_id' => $africa->id],
            ['code' => 'UG', 'name' => 'Uganda', 'continent_id' => $africa->id],
            ['code' => 'UA', 'name' => 'Ukraine', 'continent_id' => $africa->id],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'continent_id' => $africa->id],
            ['code' => 'GB', 'name' => 'United Kingdom', 'continent_id' => $africa->id],
            ['code' => 'UY', 'name' => 'Uruguay', 'continent_id' => $africa->id],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'continent_id' => $africa->id],
            ['code' => 'VE', 'name' => 'Venezuela', 'continent_id' => $africa->id],
            ['code' => 'VN', 'name' => 'Vietnam', 'continent_id' => $africa->id],
            ['code' => 'YE', 'name' => 'Yemen', 'continent_id' => $africa->id],
            ['code' => 'YU', 'name' => 'Yugoslavia', 'continent_id' => $africa->id],
            ['code' => 'ZM', 'name' => 'Zambia', 'continent_id' => $africa->id],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'continent_id' => $africa->id],
        ];

        DB::table('countries')->insert($countries);
    }
}
